# Runs tests and builds for every pull request creation and update event.

name: Run tests and build on PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test_and_build:
    name: Run tests and build on PR
    uses: guidion-digital/.github/.github/workflows/partial-test-build.yaml@GDD-5502
    secrets: inherit
    with:
      concurrency_name: "${{github.ref}}"
      disable_linting: true
